package com.pg85.otg.util.materials;

public class LegacyMaterials
{
	public static String blockNameFromLegacyBlockId(int id)
	{
		switch(id)
		{
			case 0:
				return "air";
			case 1:
				return "stone";
			case 2:
				return "grass_block";
			case 3:
				return "dirt";
			case 4:
				return "cobblestone";
			case 5:
				return "oak_planks";
			case 6:
				return "oak_sapling";
			case 7:
				return "bedrock";
			case 8:
				return "water";
			case 9:
				return "water";
			case 10:
				return "lava";
			case 11:
				return "lava";
			case 12:
				return "sand";
			case 13:
				return "gravel";
			case 14:
				return "gold_ore";
			case 15:
				return "iron_ore";
			case 16:
				return "coal_ore";
			case 17:
				return "oak_log";
			case 18:
				return "oak_leaves";
			case 19:
				return "sponge";
			case 20:
				return "glass";
			case 21:
				return "lapis_ore";
			case 22:
				return "lapis_block";
			case 23:
				return "dispenser";
			case 24:
				return "sandstone";
			case 25:
				return "note_block";
			case 26:
				return "white_bed";
			case 27:
				return "powered_rail";
			case 28:
				return "detector_rail";
			case 29:
				return "sticky_piston";
			case 30:
				return "cobweb";
			case 31:
				return "tall_grass";
			case 32:
				return "dead_bush";
			case 33:
				return "piston";
			case 34:
				return "piston_head";
			case 35:
				return "white_wool";
			case 36:
				return "piston_extension";
			case 37:
				return "dandelion";
			case 38:
				return "rose_bush";
			case 39:
				return "brown_mushroom";
			case 40:
				return "red_mushroom";
			case 41:
				return "gold_block";
			case 42:
				return "iron_block";
			case 43:
				return "smooth_stone"; // Double-slab
			case 44:
				return "stone_slab";
			case 45:
				return "bricks";
			case 46:
				return "tnt";
			case 47:
				return "bookshelf";
			case 48:
				return "mossy_cobblestone";
			case 49:
				return "obsidian";
			case 50:
				return "torch";
			case 51:
				return "fire";
			case 52:
				return "spawner";
			case 53:
				return "oak_stairs";
			case 54:
				return "chest";
			case 55:
				return "redstone_wire";
			case 56:
				return "diamond_ore";
			case 57:
				return "diamond_block";
			case 58:
				return "crafting_table";
			case 59:
				return "wheat";
			case 60:
				return "farmland";
			case 61:
				return "furnace";
			case 62:
				return "furnace"; // TODO: Should be lit
			case 63:
				return "oak_sign";
			case 64:
				return "oak_door";
			case 65:
				return "ladder";
			case 66:
				return "rail";
			case 67:
				return "stone_stairs";
			case 68:
				return "oak_wall_sign";
			case 69:
				return "lever";
			case 70:
				return "stone_pressure_plate";
			case 71:
				return "iron_door";
			case 72:
				return "oak_pressure_plate";
			case 73:
				return "redstone_ore";
			case 74:
				return "redstone_ore"; // TODO: Should be lit
			case 75:
				return "redstone_torch"; // TODO: Should be unlit
			case 76:
				return "redstone_torch"; // TODO: Should be lit
			case 77:
				return "stone_button";
			case 78:
				return "snow";
			case 79:
				return "ice";
			case 80:
				return "snow_block";
			case 81:
				return "cactus";
			case 82:
				return "clay";
			case 83:
				return "sugar_cane";
			case 84:
				return "jukebox";
			case 85:
				return "oak_fence";
			case 86:
				return "pumpkin";
			case 87:
				return "netherrack";
			case 88:
				return "soul_sand";
			case 89:
				return "glowstone";
			case 90:
				return "nether_portal";
			case 91:
				return "jack_o_lantern";
			case 92:
				return "cake";
			case 93:
				return "unpowered_repeater";
			case 94:
				return "powered_repeater";
			case 95:
				return "white_stained_glass";
			case 96:
				return "oak_trapdoor";
			case 97:
				return "infested_stone";
			case 98:
				return "stone_bricks";
			case 99:
				return "brown_mushroom_block";
			case 100:
				return "red_mushroom_block";
			case 101:
				return "iron_bars";
			case 102:
				return "glass_pane";
			case 103:
				return "melon";
			case 104:
				return "pumpkin_stem";
			case 105:
				return "melon_stem";
			case 106:
				return "vine";
			case 107:
				return "oak_fence_gate";
			case 108:
				return "brick_stairs";
			case 109:
				return "stone_brick_stairs";
			case 110:
				return "mycelium";
			case 111:
				return "lily_pad";
			case 112:
				return "nether_bricks";
			case 113:
				return "nether_brick_fence";
			case 114:
				return "nether_brick_stairs";
			case 115:
				return "nether_wart";
			case 116:
				return "enchanting_table";
			case 117:
				return "brewing_stand";
			case 118:
				return "cauldron";
			case 119:
				return "end_portal";
			case 120:
				return "end_portal_frame";
			case 121:
				return "end_stone";
			case 122:
				return "dragon_egg";
			case 123:
				return "redstone_lamp";
			case 124:
				return "redstone_lamp"; // TODO: Should be lit
			case 125:
				return "oak_planks"; // Double-slab
			case 126:
				return "oak_slab";
			case 127:
				return "cocoa";
			case 128:
				return "sandstone_stairs";
			case 129:
				return "emerald_ore";
			case 130:
				return "ender_chest";
			case 131:
				return "tripwire_hook";
			case 132:
				return "tripwire";
			case 133:
				return "emerald_block";
			case 134:
				return "spruce_stairs";
			case 135:
				return "birch_stairs";
			case 136:
				return "jungle_stairs";
			case 137:
				return "command_block";
			case 138:
				return "beacon";
			case 139:
				return "cobblestone_wall";
			case 140:
				return "flower_pot";
			case 141:
				return "carrots";
			case 142:
				return "potatoes";
			case 143:
				return "oak_button";
			case 144:
				return "skeleton_skull";
			case 145:
				return "anvil";
			case 146:
				return "trapped_chest";
			case 147:
				return "light_weighted_pressure_plate";
			case 148:
				return "heavy_weighted_pressure_plate";
			case 149:
				return "comparator"; // TODO: Should be unpowered 
			case 150:
				return "comparator"; // TODO: Should be powered
			case 151:
				return "daylight_detector";
			case 152:
				return "redstone_block";
			case 153:
				return "nether_quartz_ore";
			case 154:
				return "hopper";
			case 155:
				return "quartz_block";
			case 156:
				return "quartz_stairs";
			case 157:
				return "activator_rail";
			case 158:
				return "dropper";
			case 159:
				return "white_terracotta";
			case 160:
				return "white_stained_glass_pane";
			case 161:
				return "acacia_leaves";
			case 162:
				return "acacia_log";
			case 163:
				return "acacia_stairs";
			case 164:
				return "dark_oak_stairs";
			case 165:
				return "slime_block";
			case 166:
				return "barrier";
			case 167:
				return "iron_trapdoor";
			case 168:
				return "prismarine";
			case 169:
				return "sea_lantern";
			case 170:
				return "hay_block";
			case 171:
				return "white_carpet";
			case 172:
				return "white_terracotta";
			case 173:
				return "coal_block";
			case 174:
				return "packed_ice";
			case 175:
				return "sunflower";
			case 176:
				return "standing_banner";
			case 177:
				return "wall_banner";
			case 178:
				return "daylight_detector_inverted";
			case 179:
				return "red_sandstone";
			case 180:
				return "red_sandstone_stairs";
			case 181:
				return "red_sandstone"; // Double-slab
			case 182:
				return "red_sandstone_slab";
			case 183:
				return "spruce_fence_gate";
			case 184:
				return "birch_fence_gate";
			case 185:
				return "jungle_fence_gate";
			case 186:
				return "dark_oak_fence_gate";
			case 187:
				return "acacia_fence_gate";
			case 188:
				return "spruce_fence";
			case 189:
				return "birch_fence";
			case 190:
				return "jungle_fence";
			case 191:
				return "dark_oak_fence";
			case 192:
				return "acacia_fence";
			case 193:
				return "spruce_door";
			case 194:
				return "birch_door";
			case 195:
				return "jungle_door";
			case 196:
				return "acacia_door";
			case 197:
				return "dark_oak_door";
			case 198:
				return "end_rod";
			case 199:
				return "chorus_plant";
			case 200:
				return "chorus_flower";
			case 201:
				return "purpur_block";
			case 202:
				return "purpur_pillar";
			case 203:
				return "purpur_stairs";
			case 204:
				return "purpur_double_slab";
			case 205:
				return "purpur_slab";
			case 206:
				return "end_stone_bricks";
			case 207:
				return "beetroots";
			case 208:
				return "grass_path";
			case 209:
				return "end_gateway";
			case 210:
				return "repeating_command_block";
			case 211:
				return "chain_command_block";
			case 212:
				return "frosted_ice";
			case 213:
				return "magma_block";
			case 214:
				return "nether_wart_block";
			case 215:
				return "red_nether_bricks";
			case 216:
				return "bone_block";
			case 217:
				return "structure_void";
			case 218:
				return "observer";
			case 219:
				return "white_shulker_box";
			case 220:
				return "orange_shulker_box";
			case 221:
				return "magenta_shulker_box";
			case 222:
				return "light_blue_shulker_box";
			case 223:
				return "yellow_shulker_box";
			case 224:
				return "lime_shulker_box";
			case 225:
				return "pink_shulker_box";
			case 226:
				return "gray_shulker_box";
			case 227:
				return "light_gray_shulker_box";
			case 228:
				return "cyan_shulker_box";
			case 229:
				return "purple_shulker_box";
			case 230:
				return "blue_shulker_box";
			case 231:
				return "brown_shulker_box";
			case 232:
				return "green_shulker_box";
			case 233:
				return "red_shulker_box";
			case 234:
				return "black_shulker_box";
			case 235:
				return "white_glazed_terracotta";
			case 236:
				return "orange_glazed_terracotta";
			case 237:
				return "magenta_glazed_terracotta";
			case 238:
				return "light_blue_glazed_terracotta";
			case 239:
				return "yellow_glazed_terracotta";
			case 240:
				return "lime_glazed_terracotta";
			case 241:
				return "pink_glazed_terracotta";
			case 242:
				return "gray_glazed_terracotta";
			case 243:
				return "light_gray_glazed_terracotta";
			case 244:
				return "cyan_glazed_terracotta";
			case 245:
				return "purple_glazed_terracotta";
			case 246:
				return "blue_glazed_terracotta";
			case 247:
				return "brown_glazed_terracotta";
			case 248:
				return "green_glazed_terracotta";
			case 249:
				return "red_glazed_terracotta";
			case 250:
				return "black_glazed_terracotta";
			case 251:
				return "white_concrete";
			case 252:
				return "white_concrete_powder";
			case 255:
				return "structure_block";
			case 342:
				return "chest_minecart";
			case 343:
				return "furnace_minecart";
			case 397:
				return "skeleton_skull";
			case 404:
				return "comparator";
			case 405:
				return "nether_bricks";
			case 427:
				return "spruce_door";
			case 428:
				return "birch_door";
			case 429:
				return "jungle_door";
			case 430:
				return "acacia_door";
			case 431:
				return "dark_oak_door";
			default:
				return null;
		}
	}
}
