name: OpenTerrainGenerator
version: 1.12.2 v8.3_r1
description: Generate anything! This mod is made by PG85 and is a fork of TerrainControl, which was made by Khorn, Olof Cayorion Larsson, RutgerKok and Timethor.
authors: ['PeeGee85', 'RutgerKok', 'TimeThor', 'Khorn', 'Olof Cayorion Larsson']
main: com.pg85.otg.bukkit.OTGPlugin
load: startup
commands:
    otg:
        description: OpenTerrainGenerator commands
        usage: |
              /<command> <check> [world] - Checks if OTG is enabled for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] [-w] - Show current biome information
              /<command> <tp> [name or id] - Teleport to the given biome (name or id, max range 1000 chunks)
        aliases: [openterraingenerator]
permissions:
    otg.*:
        default: false
        children:
            otg.cmd.*: true
    otg.cmd.*:
        default: false
        children:
            otg.cmd.biome: true
            otg.cmd.check: true
            otg.cmd.help: true
            otg.cmd.list: true
            otg.cmd.map: true
            otg.cmd.reload: true
            otg.cmd.spawn: true
            otg.cmd.tp: true
    otg.cmd.biome:
        default: op
        description: show chunk biome and block stats
    otg.cmd.check:
        default: op
        description: check/create OTG settings for world
    otg.cmd.help:
        default: op
        description: show help
    otg.cmd.list:
        default: op
        description: list bo2 objects
    otg.cmd.map:
        default: op
        description: generate biome map image
    otg.cmd.reload:
        default: op
        description: reload world settings
    otg.cmd.spawn:
        default: op
        description: spawn bo2 where you look
    otg.cmd.tp:
        default: op
        description: Teleport to the given biome (name or id, max range 1000 chunks)