name: TerrainControl
version: ${version}
description: Advanced custom world generator.
authors: ['Khorn', 'Olof Cayorion Larsson']
main: com.khorn.terraincontrol.bukkit.TCPlugin
load: startup
commands:
    tc:
        description: TerrainControl commands
        usage: |
              /<command> <check> [world] - Checks TC is enable for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] [-w] - Show current biome information
        aliases: [terraincontrol]
permissions:
    tc.*:
        default: false
        children:
            tc.cmd.*: true
    tc.cmd.*:
        default: false
        children:
            tc.cmd.biome: true
            tc.cmd.check: true
            tc.cmd.help: true
            tc.cmd.list: true
            tc.cmd.map: true
            tc.cmd.reload: true
            tc.cmd.spawn: true
    tc.cmd.biome:
        default: op
        description: show chunk biome and block stats
    tc.cmd.check:
        default: op
        description: check/create TC settings for world
    tc.cmd.help:
        default: op
        description: show help
    tc.cmd.list:
        default: op
        description: list bo2 objects
    tc.cmd.map:
        default: op
        description: generate biome map image
    tc.cmd.reload:
        default: op
        description: reload world settings
    tc.cmd.spawn:
        default: op
        description: spawn bo2 where you look